version: '3'
services: 
  redis:
    image: 'redis:latest'
  worker:
    build:
      dockerfile: Dockerfile
      context: ./worker
    expose:
      - "5000"
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    volumes: 
      - ./api/routes:/app/routes
      - ./api/package.json:/app/package.json
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WORKER_HOST=worker
      - WORKER_PORT=5000
      - TOKEN_SECRET=asdfljsdfoi3429023
    depends_on: 
      - worker
    #ports: 
    #  - "3001:3001"
  server:
    stdin_open: true
    build: 
      dockerfile: Dockerfile
      context: ./server
    volumes: 
      - ./server/public:/app/public
      - ./server/src:/app/src
      - ./server/views:/app/views
      - ./server/package.json:/app/package.json
    #ports: 
    #  - "80:3000"
  nginx:
    depends_on: 
      - server
      - api
      - worker
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    ports: 
      - "80:80"
  